### ISSUE TITLE
Improve gateway logs

### ISSUE THREAD

**Issue by gr4per** [OpusCapitaBusinessNetwork/api-gw#17]
* Add tag "kong" to logger (this can be done on service create)
* Add field responseTime to gateway log (time from request passed to upstream until upstream response received)
* Add message field and create message like this message = request uri - response status, response timing

**Comment by sureshvarman-cronj** [comment]
![kibana](https://cloud.githubusercontent.com/assets/20809609/26073408/69065272-39cc-11e7-8e4a-0c662a08b6e3.png)

**Comment by sureshvarman-cronj** [comment]
@gr4per , approval need before closing this card.

**Comment by gr4per** [comment]
looks good to me
