### ISSUE TITLE
Error in user cache update, when assigning supplier to user

### ISSUE THREAD

**Issue by lasong** [OpusCapitaBusinessNetwork/api-gw#18]
When assigning a new supplier to user after a supplier has registered, we get this error:

![bildschirmfoto 2017-05-12 um 13 03 15](https://cloud.githubusercontent.com/assets/1188617/25995655/ab12986c-3713-11e7-860c-ad66034573d2.png)

This error happens in the `user` service, when it tries to update the user cache. Specifically, it happens on line `241` here:

<img width="889" alt="bildschirmfoto 2017-05-12 um 13 08 13" src="https://cloud.githubusercontent.com/assets/1188617/25995750/2af30abc-3714-11e7-9b9f-68a765b3b140.png">

The `doUserCacheUpdate` method is:

<img width="886" alt="bildschirmfoto 2017-05-12 um 13 10 09" src="https://cloud.githubusercontent.com/assets/1188617/25995794/5b4889f8-3714-11e7-93c0-bbea3bafd2f7.png">

**Comment by sureshvarman** [comment]
The case seems the user service or the supplier is not sending the cookies properly, because i have tested it on the client instead of server side, it seems working

**Comment by lasong** [comment]
Fixed by https://github.com/OpusCapita/supplier/pull/53
