### ISSUE TITLE
Consistent logging/tracing support

### ISSUE THREAD

**Issue by gr4per** [OpusCapitaBusinessNetwork/api-gw#2]
We need to be able to track exactly what happened in scope of an externally triggered request.
-Request unique id (correlation id)
-Consistent logging format and approach in the different services
-Logfile collection
-Logfile parsing/filtering

There are a couple of things to take care of in order to have this work, so I propose do do
- investigate how this problem has been solved before
- split this down to pieces and conquer

**Comment by sureshvarman-cronj** [comment]
Fixes in https://github.com/OpusCapitaBusinessNetwork/ELK, 

TODO

Have to enable the UDP plugin and Correlation plugin in API gateway

Need to propose a proper document for logging formats

**Comment by sureshvarman-cronj** [comment]
fixes for registering correlation id and UDP log plugins in https://github.com/OpusCapitaBusinessNetwork/api-gw/commit/efb82916dfe3c396daec9b374aadbeacee419727. Since the issue consists for different functionalities in different repos, not included in the issue number in commit

**Comment by sureshvarman-cronj** [comment]
Document for ELK stack and Log format is been updated at https://github.com/OpusCapitaBusinessNetwork/ELK/blob/master/Readme.md

**Comment by sureshvarman-cronj** [comment]
Reference for developer on how to use the ELK and log driver in docker-compose file are added under https://github.com/OpusCapitaBusinessNetwork/ELK/blob/master/Readme.md
